### PR TITLE
improved cloning workflow

### PR DESCRIPTION
**Pull request by dniasoff**
Hi,

Thanks for an amazing driver.

Had a couple of issues whilst testing on OpenStack.

When cloning the current driver creates a temporary snapshot, uses it to clone and then attempts to delete it which fails.

I am using Linstor on 1.27.0 on Ubuntu with ZFS 2.2.2 and due to the ZFS clone it will fail. I have changed the logic to "define" the snapshot within OpenStack, so that the user/operator is aware that it exists and OpenStack is aware of the hierarchy. (thinking that I should probably at least attempt delete the temp snapshot before defining it within OpenStack?)

Additionally, I changed the error handling when attempting to delete a snapshot/resource that is busy.

Feel free to suggest changes or reject :)

Thanks

Daniel

### CODE REVIEW

**Comment by WanzenBug** [comment]
Hi! Thanks for the contribution!

You could take a look at directly cloning: https://github.com/LINBIT/linstor-api-py/blob/master/linstor/resource.py#L690C9-L716

This also has a way for users to specify if they want "dependant snapshots" on ZFS or independant clones.

**Comment by dniasoff** [comment]
That's an idea. Thanks.

Torn whether to use ZFSCloning which will much faster and more space/ram efficient but create a mess due to hierarchy of snapshots and clones or use slower and inefficient independent clones that will be less confusing for the user.

The neatest option would be to create a config parameter?

The current code by Linstor uses [restore_from_snapshot](https://github.com/LINBIT/openstack-cinder/blob/9469045b95c3223659427cea42c9ab17e512da13/cinder/volume/drivers/linstordrv.py#L1075)

**Comment by WanzenBug** [comment]
> The neatest option would be to create a config parameter?

Seems sensible, yes

**Comment by WanzenBug** [comment]
Squashed it all into fbf8cc0f14bc8062d8f8c94f1cf1ef857b86b06a

**Pull request closed without merging**
